# Generated by Django 5.0 on 2024-08-21 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ott_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_poster', models.ImageField(upload_to='')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_release_date', models.DateTimeField(blank=True)),
                ('movie_language', models.CharField(max_length=20)),
                ('movie_director', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=500)),
                ('movie_category', models.CharField(max_length=50)),
                ('movie_description', models.TextField(max_length=5000)),
                ('movie_trailer_link', models.CharField(max_length=5000)),
                ('movie_stream_link', models.CharField(max_length=5000)),
                ('movie_imbd_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('movie_views', models.CharField(max_length=50)),
                ('is_publish', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
