# Generated by Django 5.0 on 2024-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott_app',
            name='movie_release_date',
            field=models.DateField(blank=True),
        ),
    ]
