# Generated by Django 5.0 on 2024-09-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_app', '0002_alter_ott_app_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott_app',
            name='movie_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ott_app',
            name='movie_stream_link',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='ott_app',
            name='movie_trailer_link',
            field=models.URLField(max_length=5000),
        ),
    ]
