# Generated by Django 5.0 on 2024-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_app', '0003_alter_ott_app_movie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott_app',
            name='movie_description',
            field=models.TextField(max_length=300),
        ),
    ]
